#!/bin/bash
# shorthand to move file to file.bak.
# use bak -u to revert.

case "$1" in
  -u) shift
  	for file in "$@"; do
		if [[ "${file##*.}" == "bak" ]]; then
			mv "$file" "${file%.*}"
		fi
  	done 
  	;;

  *)
	for file in "$@"; do
  		mv "$file" "$file".bak
  	done
  	;;
esac
