#!/bin/bash
# shorthand to move file to file.bak.
# use bak -u to revert.

while [[ $# -gt 0 ]]; do
  case "${1}" in
    -u) shift; mv "$1" $(basename "$1" .bak) ;;
    * ) mv "$1" "$1".bak
  esac
  shift
done
