#!/bin/bash
# shorthand to move file to file.bak.
# use bak -u to revert.

case "$1" in
  -u) shift
  	for file in "$@"; do
  		mv "$file" $(basename "$file" .bak)
  	done 
  	;;

  * ) for file in "$@"; do
  		mv "$file" "$file".bak
  	done
  	;;
esac
