#!/bin/bash
# Controls volume using pulseaudio and displays notification.

# arbitrary but unique message id
msgId="991049"

if [ -n "$1" ]; then

    # change the volume
    pulseaudio-ctl "$1" > /dev/null

    # get the current volume and whether or not the speaker is muted
    volume="$(pulseaudio-ctl full-status | cut -d' ' -f1)"
    mute="$(pulseaudio-ctl full-status | cut -d' ' -f2)"
    if [[ $volume == 0 || "$mute" == "yes" ]]; then
        # send sound muted notification
        dunstify -a "changeVolume" -u low -i audio-volume-muted -r "$msgId" "Volume muted" 
    else
        # send volume notification
        dunstify -a "changeVolume" -u low -i audio-volume-high -r "$msgId" \
        "Volume: ${volume}%" "$(get-progress-string 20 "<b>∎</b>" "─" $volume)"
    fi

    # play the volume changed sound
    canberra-gtk-play -i audio-volume-change -d "changeVolume"
else
    echo "Usage: $(basename $0) <up/down/mute>"
fi

