#!/bin/bash
# Mounts an encfs directory '.<dirname>' to '<dirname>' in present working directory.

dirname="$1"

if [ -n "$dirname" ]; then
    encfs $(pwd)/."$dirname" $(pwd)/"$dirname"
    touch "$dirname"/.borgmatic_ignore
else
    echo "Usage: $(basename $0) <dirname>"
    echo "Mounts an encfs directory '.<dirname>' to '<dirname>' in present working directory."
    echo "Adds a .borgmatic_ignore file to the open encfs archive."
fi
