#!/bin/bash
# used to quickly make a video from a sequential set of png files.
# Notes:
# # See https://trac.ffmpeg.org/wiki/Slideshow for details on creating videos from images with ffmpeg.
# # Also see https://stackoverflow.com/questions/24961127/how-to-create-a-video-from-images-with-ffmpeg for more tips.
# # The -vf option prevents issues if the pixel count is indivisible by 2. Here I take the cropping approach, though scaling or padding both are potential methods. See https://stackoverflow.com/questions/20847674/ffmpeg-libx264-height-not-divisible-by-2

framerate="$1"

ffmpeg -framerate "$framerate" -pattern_type glob -i '*.png' -c:v libx264 -pix_fmt yuv420p -vf "crop=trunc(iw/2)*2:trunc(ih/2)*2" out-$(datetime).mp4
