#!/bin/bash

systemctl disable mullvad-daemon.service
cp -i '/opt/Mullvad VPN/resources/mullvad-daemon.service' '/etc/systemd/system/'
systemctl enable mullvad-daemon.service
systemctl start mullvad-daemon.service
