#!/bin/bash

input_file="$1"
output_file=$(basename "$inputfile" .pdf)_compressed.pdf

gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile="$output_file" "$input_file"
