#!/bin/bash

if [ -e /sys/class/power_supply/BAT0 ]; then
	seconds_dim=300
	seconds_lock=300
elif [ -e /sys/class/power_supply/BAT1 ]; then
    seconds_dim=300
    seconds_lock=300
else
	seconds_dim=900
	seconds_lock=900
fi
xset s $seconds_dim $seconds_lock
xss-lock -n dim-screen -- xsecurelock
