#!/bin/bash
# a script to manage startup programs

logfile=~/.startup-log

# get window manager
function get_wm() {
    array=("i3" "sway")
    for item in "${array[@]}"; do
        if pgrep -x "$item" > /dev/null; then
            echo $item
            break
        fi
    done
}

wm=$(get_wm)


# startup options
case "$1" in
	on-boot)
		date > $logfile
		redshift -l "$redshift_location" &
		autotiling &
		startup if-battery
		startup lock
		startup noisefilter
		startup taskbar-utilities
		yadm pull &
		git -C ~/src/scripts/ pull &
	;;

	on-restart)
		startup bar
		startup keyboard-layout
		startup theme
		startup compositor
		autorandr --change
	;;

	bar)
		if [[ $wm == i3 ]]; then
			~/.config/polybar/polybar-launch mine
		elif [[ $wm == sway ]]; then
			pkill waybar
			waybar
		fi
	;;

	compositor|picom)
		if [[ $wm = i3 ]]; then
			pkill picom && sleep 1
			picom --config ~/.config/picom/picom.conf &
		fi
	;;

	if-battery)
		if [ -e /sys/class/power_supply/BAT0 ]; then
			batsignal &
		elif [ -e /sys/class/power_supply/BAT1 ]; then
			batsignal &
		fi
	;;	

	keyboard-layout)
		xmodmap ~/.Xmodmap
	;;

	lock)
		screen-locker &
	;;

	noisefilter)
		easyeffects -l NoiseFilterVoice --gapplication-service &
	;;

	taskbar-utilities)
		syncthingtray --wait &
		udiskie --no-automount --notify --smart-tray &
		indicator-sound-switcher &
		nm-applet &
		blueman-applet &
	;;

	theme)
		wallpaper=~/.local/share/wallpapers/wood-background-1.jpg 
		feh --bg-fill $wallpaper $wallpaper $wallpaper || xsetroot -solid '#111111'
		wal --theme ~/.config/wal/colorschemes/dark/batpuccin16.json &
	;;

	test)
		echo Test complete.
	;;

	help|*) 
		cat <<- EOF
		Usage: startup <option>
		  on-boot           for startup programs on boot
		  on-restart        for programs that need refresh on WM restart
		  bar               polybar
		  compositor        picom
		  if-battery        for battery based devices
		  keyboard-layout   xmodmap
		  lock              screensaver lock
		  noisefilter       noisefiltering for microphone
		  taskbar-utilities various programs that use the taskbar
		  theme             colors & theming
		EOF
esac
