#!/bin/bash
# a script to manage startup programs

logfile=~/.startup-log
exec &>> $logfile

case "$1" in
    on-boot)
		date > $logfile
        #indicator-sound-switcher &
        # ~/.config/mopidy/concat_mopidy_conf && mopidy &
        #mpd-notification --music-dir ~/Music &
        udiskie --no-automount --notify --smart-tray &
        #redshift -l $(latlong) &
        #redshift -l 47:-122 &
        nm-applet &
        pcloud &
		autorandr --change
		autotiling &
		startup if-battery
		startup lock
    ;;

    on-restart)
        startup bar
		startup theme
		startup compositor
    ;;

	if-battery)
		if [ -e /sys/class/power_supply/BAT0 ]; then
			batsignal &
		fi
	;;	

	compositor|picom)
		pkill picom && sleep 2
		picom --experimental-backends --config ~/.config/picom/picom.conf &
	;;

	bar|polybar)
		~/.config/polybar/polybar-launch mine
	;;

	theme)
		wallpaper=~/.local/share/wallpapers/moon-3440x1440.jpg 
		feh --bg-fill $wallpaper || xsetroot -solid '#111111'
		wal --theme .config/wal/colorschemes/dark/batpuccin16.json &
	;;

	keyboard-layout)
		xmodmap "~/.Xmodmap"
	;;

	lock)
		seconds_dim=200
		seconds_lock=300
		xset s $seconds_lock $seconds_dim
		xss-lock -n dim-screen -- xsecurelock &
		#xsslock -b dim-screen -- betterlockscreen --off 5 -l dim
	;;

    test)
        echo Test complete.
    ;;

    --help|*)
        cat <<- EOF
		Usage: startup --option
		  on-boot       	for startup programs on boot
		  on-restart 	   	for programs that need refresh on WM restart
		  compositor		picom
		  bar				polybar
		  theme				colors & theming
		  keyboard-layout	xmodmap
		  lock				screensaver lock
		  if-battery		for laptops and battery based devices
		  test				test
		EOF
esac
