#!/bin/bash
# Short script to manage my tdrop calls.

function get_screen_width {
	xrandr | grep primary | cut -d' ' -f4 | cut -d'x' -f1
}

function set_style_quake {
		if [[ $(get_screen_width) > 2000 ]]; then
			w="70%"
			h="80%"
			x="15%"
			y=0
		else
			w="90%"
			h="96%"
			x="5%"
			y=0
		fi
}


case "$1" in
    kitty)
		set_style_quake
		tdrop -ma -w $w -h $h -x $x -y $y kitty --name kittydrop 
    ;;

    pavucontrol)
        tdrop -ma -w 800 -h 400 -x -810 -y 30 pavucontrol
    ;;

    blueman-manager)
        tdrop -ma -w 800 -h 400 -x -810 -y 30 blueman-manager
    ;;

    zotero)
		set_style_quake
        tdrop -ma -w $w  -h $h -x $x -y $y zotero
    ;;
    
    *)
        cat <<- EOF
		Usage: tdrops <option>
		options: kitty, pavucontrol, blueman-manager, zotero
		EOF
esac
